export const S3_URL = "https://s3.amazonaws.com/io.cribl.c021.takehome/cribl.log";
export const DEFAULT_ITEM_HEIGHT = 50;
export const DEFAULT_BORDER_COLOR = "#ced9e0";
export const PRIMARY_BACKGROUND_COLOR = "#fff";
export const SECONDARY_BACKGROUND_COLOR = "#f5f8fa";
export const TERTIARY_BACKGROUND_COLOR = "#ebf1f4";
export const PRIMARY_LOADING_COLOR = "#e0e0e0";
export const SECONDARY_LOADING_COLOR = "#c0c0c0";
export const DEFAULT_FONT_FAMILY = "Open Sans, sans-serif";
